### ISSUE TITLE
training time for you to train cifar10 with single Titan GPU

### ISSUE THREAD

**Issue by cucutone** [leftthomas/MoCo#1]
Hi, thank you for sharing this moco implementation. 
I would like to ask how much time did you train on cifar10 with a single TITAN GPU and is 50 epochs enough for convergence?
Also how do you set the queue size and temperature? I saw some other implementations on ImageNet and those hyperparameters are so different. Is there any clue about setting hyperparameter for small datasets?
Thank you and look forward to your reply!

**Comment by leftthomas** [comment]
@cucutone about training time, try by yourself, about hyper-parameter, I follow the paper.
