### ISSUE TITLE
Can you explain the basis for doing so? Why is this equivalent to shuffling BN? 

### ISSUE THREAD

**Issue by DiaosWang** [leftthomas/MoCo#3]
https://github.com/leftthomas/MoCo/blob/69b40e2d68f1e1fc3d12eee8d2eccd87e2ee1d6f/train.py#L23C1-L26C38

**Comment by DiaosWang** [comment]
@leftthomas hello，帅哥在吗?

**Comment by Mrmuran** [comment]
> https://github.com/leftthomas/MoCo/blob/69b40e2d68f1e1fc3d12eee8d2eccd87e2ee1d6f/train.py#L23C1-L26C38

I have the same doubts

**Comment by leftthomas** [comment]
@Mrmuran The fundamental purpose of shuffling BN is to prevent the model from learning a specific data order, which is why it disrupts and ensures that the model does not pass this order back when it is in the BP, so essentially as long as it can ensure this.

**Comment by Mrmuran** [comment]
> @Mrmuran The fundamental purpose of shuffling BN is to prevent the model from learning a specific data order, which is why it disrupts and ensures that the model does not pass this order back when it is in the BP, so essentially as long as it can ensure this.

Emmm,i think i understand what you mean.Thanks for your respond!

**Comment by athenacon** [comment]
Hello, thanks for the implementation, but would you be able to please explain why this works for single-GPU for the BN?

**Comment by leftthomas** [comment]
@athenacon https://github.com/leftthomas/MoCo/issues/3#issuecomment-1818756101
